# Cedeon task runner. Install `just`: https://github.com/casey/just
set dotenv-load := true
set positional-arguments := true

api_dir := "apps/api"
web_dir := "apps/web"

# List tasks
default:
    @just --list

# --- Environment ---

# First-time setup: install all deps, prepare .env, generate the typed API client
bootstrap:
    test -f .env || cp .env.example .env
    cd {{api_dir}} && uv sync --all-extras
    cd {{web_dir}} && pnpm install
    just gen-client

# Bring up the full local stack (postgres, minio, api, worker, web)
up:
    docker compose -f infra/docker-compose.yml up --build -d
    @echo "web  → http://localhost:3000"
    @echo "api  → http://localhost:8000/docs (proxied at http://localhost:3000/api)"
    @echo "minio→ http://localhost:9101 (cedeon / cedeon-secret)"

down:
    docker compose -f infra/docker-compose.yml down

logs service="":
    docker compose -f infra/docker-compose.yml logs -f {{service}}

# --- Database ---

migrate:
    cd {{api_dir}} && uv run alembic upgrade head

# Create a new autogenerated migration: just revision "add widgets"
revision message:
    cd {{api_dir}} && uv run alembic revision --autogenerate -m "{{message}}"

downgrade target="-1":
    cd {{api_dir}} && uv run alembic downgrade {{target}}

# Wipe and recreate the local database (destructive)
db-reset:
    docker compose -f infra/docker-compose.yml exec -T postgres \
      psql -U cedeon -d postgres -c "DROP DATABASE IF EXISTS cedeon;" -c "CREATE DATABASE cedeon;"
    just migrate

seed-demo:
    cd {{api_dir}} && uv run python -m app.scripts.seed_demo

# --- Dev servers (without docker) ---

api-dev:
    cd {{api_dir}} && uv run uvicorn app.main:app --reload --port 8000

worker-dev:
    cd {{api_dir}} && uv run procrastinate --app=app.jobs.app.procrastinate_app worker

web-dev:
    cd {{web_dir}} && pnpm dev

# --- Quality gates ---

test: test-api test-web

test-api:
    cd {{api_dir}} && uv run pytest

test-web:
    cd {{web_dir}} && pnpm test run

lint:
    cd {{api_dir}} && uv run ruff check . && uv run ruff format --check .
    cd {{web_dir}} && pnpm lint

fmt:
    cd {{api_dir}} && uv run ruff check --fix . && uv run ruff format .
    cd {{web_dir}} && pnpm format

typecheck:
    cd {{api_dir}} && uv run mypy app
    cd {{api_dir}} && uv run lint-imports
    cd {{web_dir}} && pnpm typecheck

build:
    cd {{web_dir}} && pnpm build

# Regenerate the typed API client from the live/local OpenAPI schema
gen-client:
    cd {{api_dir}} && uv run python -m app.scripts.export_openapi > ../../packages/openapi/openapi.json
    cd {{web_dir}} && pnpm gen:client

# Full CI-equivalent run
ci: lint typecheck test build
