"""reinsurance structure

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-30 06:44:38.142668+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cedents",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_cedents_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cedents")),
        sa.UniqueConstraint("organization_id", "name", name="uq_cedents_org_name"),
    )
    op.create_table(
        "reinsurers",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reinsurers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reinsurers")),
        sa.UniqueConstraint("organization_id", "name", name="uq_reinsurers_org_name"),
    )
    op.create_table(
        "reinsurance_programs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("cedent_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("treaty_year", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cedent_id"],
            ["cedents.id"],
            name=op.f("fk_reinsurance_programs_cedent_id_cedents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reinsurance_programs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reinsurance_programs")),
        sa.UniqueConstraint(
            "organization_id", "cedent_id", "name", name="uq_programs_org_cedent_name"
        ),
    )
    op.create_index(
        "ix_reinsurance_programs_cedent_id", "reinsurance_programs", ["cedent_id"], unique=False
    )
    op.create_table(
        "treaties",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column(
            "treaty_type",
            sa.Enum("PER_OCCURRENCE_XOL", name="treaty_type", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_treaties_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["reinsurance_programs.id"],
            name=op.f("fk_treaties_program_id_reinsurance_programs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_treaties")),
    )
    op.create_index("ix_treaties_program_id", "treaties", ["program_id"], unique=False)
    op.create_table(
        "treaty_versions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("treaty_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PARSING",
                "EXTRACTING",
                "NEEDS_VALIDATION",
                "VALIDATED",
                "ACTIVE",
                "SUPERSEDED",
                name="treaty_version_status",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("validated_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_treaty_versions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
            name=op.f("fk_treaty_versions_source_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["treaty_id"],
            ["treaties.id"],
            name=op.f("fk_treaty_versions_treaty_id_treaties"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["validated_by"],
            ["users.id"],
            name=op.f("fk_treaty_versions_validated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_treaty_versions")),
        sa.UniqueConstraint("treaty_id", "version_no", name="uq_treaty_versions_treaty_version_no"),
    )
    op.create_index("ix_treaty_versions_treaty_id", "treaty_versions", ["treaty_id"], unique=False)
    op.create_table(
        "treaty_layers",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("treaty_version_id", sa.Uuid(), nullable=False),
        sa.Column("layer_no", sa.Integer(), nullable=False),
        sa.Column("attachment", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("limit", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reinstatements", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_treaty_layers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["treaty_version_id"],
            ["treaty_versions.id"],
            name=op.f("fk_treaty_layers_treaty_version_id_treaty_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_treaty_layers")),
        sa.UniqueConstraint(
            "treaty_version_id", "layer_no", name="uq_treaty_layers_version_layer_no"
        ),
    )
    op.create_table(
        "treaty_participations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("treaty_version_id", sa.Uuid(), nullable=False),
        sa.Column("reinsurer_id", sa.Uuid(), nullable=False),
        sa.Column("placed_share", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("signed_share", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("broker_name", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_treaty_participations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reinsurer_id"],
            ["reinsurers.id"],
            name=op.f("fk_treaty_participations_reinsurer_id_reinsurers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["treaty_version_id"],
            ["treaty_versions.id"],
            name=op.f("fk_treaty_participations_treaty_version_id_treaty_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_treaty_participations")),
        sa.UniqueConstraint(
            "treaty_version_id", "reinsurer_id", name="uq_treaty_participations_version_reinsurer"
        ),
    )
    op.create_table(
        "treaty_terms",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("treaty_version_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CONFIRMED",
                "AMBIGUOUS",
                "REJECTED",
                name="treaty_term_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("derived_from_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("review_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_treaty_terms_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["treaty_version_id"],
            ["treaty_versions.id"],
            name=op.f("fk_treaty_terms_treaty_version_id_treaty_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_treaty_terms")),
        sa.UniqueConstraint("treaty_version_id", "key", name="uq_treaty_terms_version_key"),
    )

    # Circular reference: added after both tables exist.
    op.create_foreign_key(
        op.f("fk_treaties_current_version_id_treaty_versions"),
        "treaties",
        "treaty_versions",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f("fk_treaties_current_version_id_treaty_versions"), "treaties", type_="foreignkey"
    )
    op.drop_table("treaty_terms")
    op.drop_table("treaty_participations")
    op.drop_table("treaty_layers")
    op.drop_index("ix_treaty_versions_treaty_id", table_name="treaty_versions")
    op.drop_table("treaty_versions")
    op.drop_index("ix_treaties_program_id", table_name="treaties")
    op.drop_table("treaties")
    op.drop_index("ix_reinsurance_programs_cedent_id", table_name="reinsurance_programs")
    op.drop_table("reinsurance_programs")
    op.drop_table("reinsurers")
    op.drop_table("cedents")
    # ### end Alembic commands ###
