"""extraction and review

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-30 07:02:15.046511+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_versions",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_versions")),
        sa.UniqueConstraint("name", "version", name="uq_prompt_versions_name_version"),
    )
    op.create_table(
        "agent_runs",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "agent_type",
            sa.Enum(
                "TREATY_EXTRACTION",
                "RECOVERY_INVESTIGATOR",
                "NOTICE_DRAFTER",
                name="agent_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("subject_type", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=80), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                name="agent_run_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("input_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_runs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(
        "ix_agent_runs_org_created", "agent_runs", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_agent_runs_subject", "agent_runs", ["subject_type", "subject_id"], unique=False
    )
    op.create_table(
        "reviews",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "subject_type",
            sa.Enum(
                "TREATY_TERM_CANDIDATE",
                "TREATY_PARTICIPATION_SET",
                "RECOVERY_CANDIDATE",
                "RECOVERY_PACKET",
                "RECOVERY_NOTICE",
                name="review_subject_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "CONFIRM",
                "EDIT",
                "REJECT",
                "MARK_AMBIGUOUS",
                "REQUEST_INFO",
                name="review_decision",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("value_before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("value_after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reviews_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_reviews_reviewer_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
    )
    op.create_index("ix_reviews_subject", "reviews", ["subject_type", "subject_id"], unique=False)
    op.create_table(
        "citations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=500), nullable=True),
        sa.Column("quoted_text", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=True),
        sa.Column("char_end", sa.Integer(), nullable=True),
        sa.Column("chunk_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_citations_chunk_id_document_chunks"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_citations_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_citations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_citations")),
    )
    op.create_index("ix_citations_document_id", "citations", ["document_id"], unique=False)
    op.create_table(
        "treaty_term_candidates",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("treaty_version_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "EXTRACTED",
                "NOT_FOUND",
                "AMBIGUOUS",
                "CONFLICTING",
                name="candidate_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("raw_value", sa.Text(), nullable=True),
        sa.Column("normalized_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("citation_id", sa.Uuid(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("resolution", sa.String(length=24), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_treaty_term_candidates_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["citation_id"],
            ["citations.id"],
            name=op.f("fk_treaty_term_candidates_citation_id_citations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_treaty_term_candidates_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["treaty_version_id"],
            ["treaty_versions.id"],
            name=op.f("fk_treaty_term_candidates_treaty_version_id_treaty_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_treaty_term_candidates")),
    )
    op.create_index(
        "ix_treaty_term_candidates_version",
        "treaty_term_candidates",
        ["treaty_version_id"],
        unique=False,
    )
    op.add_column("treaty_terms", sa.Column("currency", sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("treaty_terms", "currency")
    op.drop_index("ix_treaty_term_candidates_version", table_name="treaty_term_candidates")
    op.drop_table("treaty_term_candidates")
    op.drop_index("ix_citations_document_id", table_name="citations")
    op.drop_table("citations")
    op.drop_index("ix_reviews_subject", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_agent_runs_subject", table_name="agent_runs")
    op.drop_index("ix_agent_runs_org_created", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_table("prompt_versions")
    # ### end Alembic commands ###
