"""loss import

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-30 12:53:27.969049+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loss_imports",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=150), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("header_columns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "column_mapping",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "MAPPED",
                "VALIDATED",
                "COMMITTED",
                "FAILED",
                name="loss_import_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_loss_imports_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_loss_imports_uploaded_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loss_imports")),
    )
    op.create_index(
        "ix_loss_imports_org_created",
        "loss_imports",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "loss_import_rows",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("loss_import_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("parsed", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OK",
                "WARNING",
                "ERROR",
                "SKIPPED",
                name="loss_row_status",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column(
            "issues",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["loss_import_id"],
            ["loss_imports.id"],
            name=op.f("fk_loss_import_rows_loss_import_id_loss_imports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_loss_import_rows_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loss_import_rows")),
        sa.UniqueConstraint("loss_import_id", "row_number", name="uq_loss_import_rows_import_row"),
    )
    op.create_table(
        "loss_events",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("program_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("event_identifier", sa.String(length=200), nullable=True),
        sa.Column("catastrophe_code", sa.String(length=50), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("date_of_loss_from", sa.Date(), nullable=True),
        sa.Column("date_of_loss_to", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_loss_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["reinsurance_programs.id"],
            name=op.f("fk_loss_events_program_id_reinsurance_programs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loss_events")),
    )
    op.create_index("ix_loss_events_org", "loss_events", ["organization_id"], unique=False)
    op.create_table(
        "underlying_losses",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("loss_event_id", sa.Uuid(), nullable=True),
        sa.Column("loss_import_id", sa.Uuid(), nullable=False),
        sa.Column("loss_import_row_id", sa.Uuid(), nullable=False),
        sa.Column("claim_id", sa.String(length=200), nullable=False),
        sa.Column("date_of_loss", sa.Date(), nullable=False),
        sa.Column("reported_date", sa.Date(), nullable=True),
        sa.Column("gross_incurred", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("gross_paid", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("gross_case_reserve", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=60), nullable=True),
        sa.Column("cause_of_loss", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "gross_incurred >= 0", name=op.f("ck_underlying_losses_gross_incurred_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["loss_event_id"],
            ["loss_events.id"],
            name=op.f("fk_underlying_losses_loss_event_id_loss_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["loss_import_id"],
            ["loss_imports.id"],
            name=op.f("fk_underlying_losses_loss_import_id_loss_imports"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["loss_import_row_id"],
            ["loss_import_rows.id"],
            name=op.f("fk_underlying_losses_loss_import_row_id_loss_import_rows"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_underlying_losses_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_underlying_losses")),
        sa.UniqueConstraint("loss_import_row_id", name="uq_underlying_losses_import_row"),
    )
    op.create_index(
        "ix_underlying_losses_event", "underlying_losses", ["loss_event_id"], unique=False
    )
    op.create_index(
        "ix_underlying_losses_org", "underlying_losses", ["organization_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_underlying_losses_org", table_name="underlying_losses")
    op.drop_index("ix_underlying_losses_event", table_name="underlying_losses")
    op.drop_table("underlying_losses")
    op.drop_index("ix_loss_events_org", table_name="loss_events")
    op.drop_table("loss_events")
    op.drop_table("loss_import_rows")
    op.drop_index("ix_loss_imports_org_created", table_name="loss_imports")
    op.drop_table("loss_imports")
    # ### end Alembic commands ###
