"""recovery candidates

Revision ID: ff7370e89ab3
Revises: 0005
Create Date: 2026-08-30 13:33:48.666394+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recovery_candidates",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("treaty_id", sa.Uuid(), nullable=False),
        sa.Column("treaty_version_id", sa.Uuid(), nullable=False),
        sa.Column("treaty_layer_id", sa.Uuid(), nullable=False),
        sa.Column("loss_event_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "NEEDS_REVIEW",
                "IN_REVIEW",
                "CONFIRMED",
                "REJECTED",
                "NOTICE_DRAFTED",
                name="recovery_candidate_status",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("gross_event_incurred", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("currency_mismatch", sa.Boolean(), nullable=False),
        sa.Column("current_calculation_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_recovery_candidates_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["loss_event_id"],
            ["loss_events.id"],
            name=op.f("fk_recovery_candidates_loss_event_id_loss_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_recovery_candidates_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_recovery_candidates_reviewed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["treaty_id"],
            ["treaties.id"],
            name=op.f("fk_recovery_candidates_treaty_id_treaties"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["treaty_layer_id"],
            ["treaty_layers.id"],
            name=op.f("fk_recovery_candidates_treaty_layer_id_treaty_layers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["treaty_version_id"],
            ["treaty_versions.id"],
            name=op.f("fk_recovery_candidates_treaty_version_id_treaty_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_candidates")),
        sa.UniqueConstraint(
            "treaty_version_id",
            "treaty_layer_id",
            "loss_event_id",
            name="uq_recovery_candidates_version_layer_event",
        ),
    )
    op.create_index(
        "ix_recovery_candidates_loss_event_id",
        "recovery_candidates",
        ["loss_event_id"],
        unique=False,
    )
    op.create_index(
        "ix_recovery_candidates_org_status",
        "recovery_candidates",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_table(
        "recovery_calculations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("recovery_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("engine_version", sa.String(length=20), nullable=False),
        sa.Column("treaty_version_id", sa.Uuid(), nullable=False),
        sa.Column("treaty_layer_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gross_loss", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("attachment", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("amount_above_attachment", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("layer_limit", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("layer_recovery", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("cedent_retention", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("total_ceded", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("trace", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_recovery_calculations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recovery_candidate_id"],
            ["recovery_candidates.id"],
            name=op.f("fk_recovery_calculations_recovery_candidate_id_recovery_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["treaty_layer_id"],
            ["treaty_layers.id"],
            name=op.f("fk_recovery_calculations_treaty_layer_id_treaty_layers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["treaty_version_id"],
            ["treaty_versions.id"],
            name=op.f("fk_recovery_calculations_treaty_version_id_treaty_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_calculations")),
    )
    op.create_index(
        "ix_recovery_calculations_candidate_id",
        "recovery_calculations",
        ["recovery_candidate_id"],
        unique=False,
    )
    op.create_index(
        "ix_recovery_calculations_input_hash", "recovery_calculations", ["input_hash"], unique=False
    )
    op.create_table(
        "recovery_allocations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("recovery_calculation_id", sa.Uuid(), nullable=False),
        sa.Column("reinsurer_id", sa.Uuid(), nullable=False),
        sa.Column("participation_share", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("allocated_recovery", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_recovery_allocations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recovery_calculation_id"],
            ["recovery_calculations.id"],
            name=op.f("fk_recovery_allocations_recovery_calculation_id_recovery_calculations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reinsurer_id"],
            ["reinsurers.id"],
            name=op.f("fk_recovery_allocations_reinsurer_id_reinsurers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_allocations")),
        sa.UniqueConstraint(
            "recovery_calculation_id",
            "reinsurer_id",
            name="uq_recovery_allocations_calculation_reinsurer",
        ),
    )
    # Circular reference (candidate.current_calculation_id ↔ calculation.recovery_candidate_id):
    # added after both tables exist so `alembic check` sees it as a real constraint.
    op.create_foreign_key(
        op.f("fk_recovery_candidates_current_calculation_id_recovery_calculations"),
        "recovery_candidates",
        "recovery_calculations",
        ["current_calculation_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_recovery_candidates_current_calculation_id_recovery_calculations"),
        "recovery_candidates",
        type_="foreignkey",
    )
    op.drop_table("recovery_allocations")
    op.drop_index("ix_recovery_calculations_input_hash", table_name="recovery_calculations")
    op.drop_index("ix_recovery_calculations_candidate_id", table_name="recovery_calculations")
    op.drop_table("recovery_calculations")
    op.drop_index("ix_recovery_candidates_org_status", table_name="recovery_candidates")
    op.drop_index("ix_recovery_candidates_loss_event_id", table_name="recovery_candidates")
    op.drop_table("recovery_candidates")
    # ### end Alembic commands ###
