"""recovery investigator

Revision ID: b10e120d9032
Revises: 0006
Create Date: 2026-08-30 14:02:10.505284+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_calls",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OK", "ERROR", name="tool_call_status", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_tool_calls_agent_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tool_calls_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_calls")),
        sa.UniqueConstraint("agent_run_id", "ordinal", name="uq_tool_calls_run_ordinal"),
    )
    op.create_table(
        "recovery_investigations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("recovery_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="recovery_investigation_status",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "applicability_assessment",
            sa.Enum(
                "SUPPORTED",
                "PARTIALLY_SUPPORTED",
                "UNCLEAR",
                "CONTRADICTED",
                name="applicability_assessment",
                native_enum=False,
                length=24,
            ),
            nullable=True,
        ),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("out_of_scope", sa.Boolean(), nullable=False),
        sa.Column("suspected_prompt_injection", sa.Boolean(), nullable=False),
        sa.Column("unresolved_questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_recovery_investigations_agent_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_recovery_investigations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recovery_candidate_id"],
            ["recovery_candidates.id"],
            name=op.f("fk_recovery_investigations_recovery_candidate_id_recovery_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_investigations")),
    )
    op.create_index(
        "ix_recovery_investigations_candidate",
        "recovery_investigations",
        ["recovery_candidate_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "recovery_investigation_findings",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "RELEVANT_CLAUSE",
                "SUPPORTING_EVIDENCE",
                "MISSING_INFORMATION",
                "AMBIGUITY",
                "INCONSISTENCY",
                "NOTICE_OBLIGATION",
                "NEXT_STEP",
                name="finding_kind",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("citation_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["citation_id"],
            ["citations.id"],
            name=op.f("fk_recovery_investigation_findings_citation_id_citations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["recovery_investigations.id"],
            name=op.f(
                "fk_recovery_investigation_findings_investigation_id_recovery_investigations"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_recovery_investigation_findings_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_investigation_findings")),
        sa.UniqueConstraint(
            "investigation_id", "ordinal", name="uq_recovery_investigation_findings_ordinal"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recovery_investigation_findings")
    op.drop_index("ix_recovery_investigations_candidate", table_name="recovery_investigations")
    op.drop_table("recovery_investigations")
    op.drop_table("tool_calls")
    # ### end Alembic commands ###
