"""recovery packet

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-30 14:35:28.947880+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recovery_packets",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("recovery_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "human_overrides",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_recovery_packets_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_recovery_packets_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recovery_candidate_id"],
            ["recovery_candidates.id"],
            name=op.f("fk_recovery_packets_recovery_candidate_id_recovery_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_packets")),
        sa.UniqueConstraint("recovery_candidate_id", name="uq_recovery_packets_candidate"),
    )
    op.create_table(
        "recovery_packet_versions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("recovery_packet_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "APPROVED",
                "REJECTED",
                "SUPERSEDED",
                name="recovery_packet_version_status",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rendered_html", sa.Text(), nullable=True),
        sa.Column("calculation_id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=True),
        sa.Column("generated_by", sa.Uuid(), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_recovery_packet_versions_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["calculation_id"],
            ["recovery_calculations.id"],
            name=op.f("fk_recovery_packet_versions_calculation_id_recovery_calculations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"],
            ["users.id"],
            name=op.f("fk_recovery_packet_versions_generated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["recovery_investigations.id"],
            name=op.f("fk_recovery_packet_versions_investigation_id_recovery_investigations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_recovery_packet_versions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recovery_packet_id"],
            ["recovery_packets.id"],
            name=op.f("fk_recovery_packet_versions_recovery_packet_id_recovery_packets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_packet_versions")),
        sa.UniqueConstraint(
            "recovery_packet_id", "version_no", name="uq_recovery_packet_versions_no"
        ),
    )
    # Circular reference — added after both tables exist so `alembic check` stays clean.
    op.create_foreign_key(
        op.f("fk_recovery_packets_current_version_id_recovery_packet_versions"),
        "recovery_packets",
        "recovery_packet_versions",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_recovery_packets_current_version_id_recovery_packet_versions"),
        "recovery_packets",
        type_="foreignkey",
    )
    op.drop_table("recovery_packet_versions")
    op.drop_table("recovery_packets")
    # ### end Alembic commands ###
