"""recovery notice

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-30 15:03:09.868743+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recovery_notices",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("recovery_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("recovery_packet_version_id", sa.Uuid(), nullable=True),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "INITIAL_LOSS_ADVICE",
                "REINSURER_NOTIFICATION",
                name="recovery_notice_kind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "APPROVED",
                "REJECTED",
                "SUPERSEDED",
                name="recovery_notice_status",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("recipient", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("body_markdown", sa.Text(), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "key_figures",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "caveats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("used_only_provided_facts", sa.Boolean(), nullable=False),
        sa.Column("notes_for_reviewer", sa.Text(), nullable=True),
        sa.Column("generated_by", sa.Uuid(), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_recovery_notices_agent_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("fk_recovery_notices_approved_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"],
            ["users.id"],
            name=op.f("fk_recovery_notices_generated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_recovery_notices_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recovery_candidate_id"],
            ["recovery_candidates.id"],
            name=op.f("fk_recovery_notices_recovery_candidate_id_recovery_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recovery_packet_version_id"],
            ["recovery_packet_versions.id"],
            name=op.f("fk_recovery_notices_recovery_packet_version_id_recovery_packet_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_notices")),
    )
    op.create_index(
        "ix_recovery_notices_candidate",
        "recovery_notices",
        ["recovery_candidate_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_recovery_notices_candidate", table_name="recovery_notices")
    op.drop_table("recovery_notices")
    # ### end Alembic commands ###
