"""recoverables

Revision ID: 024afe2ec053
Revises: 0009
Create Date: 2026-08-31 03:09:15.377389+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recoverables",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("recovery_candidate_id", sa.Uuid(), nullable=False),
        sa.Column("recovery_calculation_id", sa.Uuid(), nullable=False),
        sa.Column("reinsurer_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "NOTIFIED",
                "AGREED",
                "BILLED",
                "COLLECTED",
                "DISPUTED",
                "WRITTEN_OFF",
                name="recoverable_status",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("expected_amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("agreed_amount", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("billed_amount", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column(
            "collected_amount",
            sa.Numeric(precision=20, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("agreed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("billed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("collected_amount >= 0", name=op.f("ck_recoverables_collected_nonneg")),
        sa.CheckConstraint("expected_amount >= 0", name=op.f("ck_recoverables_expected_nonneg")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_recoverables_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recovery_calculation_id"],
            ["recovery_calculations.id"],
            name=op.f("fk_recoverables_recovery_calculation_id_recovery_calculations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recovery_candidate_id"],
            ["recovery_candidates.id"],
            name=op.f("fk_recoverables_recovery_candidate_id_recovery_candidates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reinsurer_id"],
            ["reinsurers.id"],
            name=op.f("fk_recoverables_reinsurer_id_reinsurers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recoverables")),
        sa.UniqueConstraint(
            "recovery_candidate_id", "reinsurer_id", name="uq_recoverables_candidate_reinsurer"
        ),
    )
    op.create_index(
        "ix_recoverables_org_status", "recoverables", ["organization_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_recoverables_org_status", table_name="recoverables")
    op.drop_table("recoverables")
    # ### end Alembic commands ###
