"""loss event occurrence basis

Revision ID: 0011
Revises: 0010
Create Date: 2026-08-31 03:45:03.016637+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("loss_events", sa.Column("peril", sa.String(length=80), nullable=True))
    op.add_column("loss_events", sa.Column("hours_clause_hours", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("loss_events", "hours_clause_hours")
    op.drop_column("loss_events", "peril")
    # ### end Alembic commands ###
