"""recovery candidate knowledge date

Revision ID: 0012
Revises: 0011
Create Date: 2026-08-31 21:20:47.459293+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recovery_candidates", sa.Column("knowledge_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recovery_candidates", "knowledge_date")
    # ### end Alembic commands ###
