"""recovery candidate drift

Revision ID: 0013
Revises: 0012
Create Date: 2026-08-31 21:33:07.181731+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recovery_candidates", sa.Column("drifted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "recovery_candidates",
        sa.Column("pre_drift_recovery", sa.Numeric(precision=20, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recovery_candidates", "pre_drift_recovery")
    op.drop_column("recovery_candidates", "drifted_at")
    # ### end Alembic commands ###
